version: '3'

services:
  
  database:
    image: mysql:8
    container_name: 'database'
    ports:
      - 3306:3306
    tty: true
    expose:
      - 3306
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE : 'my_db'
      MYSQL_TCP_PORT: 3306